/*
 * SPDX-License-Identifier: GPL-2.0-only
 * Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
 */

#ifndef _DMAHAL_REG_H_
#define _DMAHAL_REG_H_

#include "dmahal_reg_i.h"

/*
 * Registers names
 *
 * NOTE:: Any change to this enum, need to change to ecpri_dma_reg_name_to_str
 *	array as well.
 */
enum ecpri_dma_hal_reg_name {
    ECPRI_HW_PARAMS_0,
    ECPRI_HW_PARAMS_2,
    ECPRI_NFAPI_CFG_0,
    ECPRI_NFAPI_CFG_1,
    ECPRI_NFAPI_CFG_2,
    ECPRI_NFAPI_REASSEMBLY_CFG_0,
    ECPRI_NFAPI_REASSEMBLY_FEC_0,
    ECPRI_NFAPI_REASSEMBLY_FEC_1,
    ECPRI_NFAPI_REASSEMBLY_FEC_2,
    ECPRI_NFAPI_REASSEMBLY_FEC_3,
    ECPRI_NFAPI_REASSEMBLY_FEC_4,
    ECPRI_NFAPI_REASSEMBLY_FEC_5,
    ECPRI_NFAPI_REASSEMBLY_ERROR_BAD_TOTAL_SDU_LENGTH_PKT_CNT,
    ECPRI_NFAPI_REASSEMBLY_ERROR_BAD_TOTAL_SDU_LENGTH_BYTE_CNT_LSB,
    ECPRI_NFAPI_REASSEMBLY_ERROR_BAD_TOTAL_SDU_LENGTH_BYTE_CNT_MSB,
    ECPRI_NFAPI_REASSEMBLY_ERROR_BAD_TIMESTAMP_PKT_CNT,
    ECPRI_NFAPI_REASSEMBLY_ERROR_BAD_TIMESTAMP_BYTE_CNT_LSB,
    ECPRI_NFAPI_REASSEMBLY_ERROR_BAD_TIMESTAMP_BYTE_CNT_MSB,
    ECPRI_NFAPI_REASSEMBLY_ERROR_PACKET_BIGGER_THAN_SDU_LENGTH_PKT_CNT,
    ECPRI_NFAPI_REASSEMBLY_ERROR_PACKET_BIGGER_THAN_SDU_LENGTH_BYTE_CNT_LSB,
    ECPRI_NFAPI_REASSEMBLY_ERROR_PACKET_BIGGER_THAN_SDU_LENGTH_BYTE_CNT_MSB,
    ECPRI_NFAPI_REASSEMBLY_ERROR_MESSAGE_BYTES_BIGGER_THAN_SDU_LENGTH_PKT_CNT,
    ECPRI_NFAPI_REASSEMBLY_ERROR_MESSAGE_BYTES_BIGGER_THAN_SDU_LENGTH_BYTE_CNT_LSB,
    ECPRI_NFAPI_REASSEMBLY_ERROR_MESSAGE_BYTES_BIGGER_THAN_SDU_LENGTH_BYTE_CNT_MSB,
    ECPRI_NFAPI_REASSEMBLY_STATE,
    ECPRI_DMA_STREAM_CTRL,
    ECPRI_DMA_STREAM_STATUS,
    ECPRI_DMA_STREAM_ARB,
    ECPRI_DMA_FL_PACKET_ID_CTRL,
    ECPRI_DMA_FL_PACKET_ID_STATUS,
    ECPRI_DMA_FL_MEMORY_SECTOR_CTRL,
    ECPRI_DMA_FL_MEMORY_SECTOR_STATUS,
    ECPRI_DMA_XBAR,
    ECPRI_DMA_DBG_CTRL,
    ECPRI_DMA_GBL_CFG,
    ECPRI_DMA_TESTBUS_CTRL,
    ECPRI_DMA_GP_REG3,
    ECPRI_DMA_AOS_FIFO_STAT,
    ECPRI_DMA_GP_STAT1,
    ECPRI_DMA_TESTBUS,
    ECPRI_DMA_GP_STAT3,
    ECPRI_DMA_IDLE_REG,
    ECPRI_DMA_EXCEPTION_CHANNEL,
    ECPRI_DMA_PKT_DROP_FULL,
    ECPRI_DMA_PKT_DROP_RE_EMPTY,
    ECPRI_DMA_DPL_CFG,
    ECPRI_DMA_TPDM_CFG,
    ECPRI_NSO_CFG,
    ECPRI_NSO_JUMBO_PKT_CFG,
    ECPRI_NSO_SHORT_PKT_CFG,
    ECPRI_NSO_LEN_ERR_STATUS_1,
    ECPRI_NSO_LEN_ERR_STATUS_2,
    ECPRI_NSO_LEN_ERR_STATUS_3,
    ECPRI_NSO_DBG_MISC_INFO,
    ECPRI_NSO_JUMBO_PKT_EN,
    ECPRI_NSO_LEN_ERR_STATUS_HDR_n,
    ECPRI_NSO_DBG_CNTXT_n_INFO_1,
    ECPRI_NSO_DBG_CNTXT_n_INFO_2,
    ECPRI_IRQ_STTS_EE_n,
    ECPRI_IRQ_EN_EE_n,
    ECPRI_IRQ_CLR_EE_n,
    ECPRI_ENDP_CFG_DEST,
    ECPRI_ENDP_CFG_XBAR,
    ECPRI_ENDP_CFG_AGGR,
    ECPRI_ENDP_NFAPI_REASSEMBLY_CFG,
    ECPRI_ENDP_INIT_CTRL_STATUS,
    ECPRI_ENDP_AXI_ATTR,
    ECPRI_ENDP_YELLOW_RED_MARKER_CFG,
    ECPRI_ENDP_GSI_CONS_BYTES_TLV,
    ECPRI_ENDP_GSI_CONS_BYTES_AOS,
    ECPRI_ENDP_GSI_IF_FIFO_CFG_TLV,
    ECPRI_ENDP_GSI_IF_FIFO_CFG_AOS,
    ECPRI_ENDP_CFG_VFID,
    ECPRI_ENDP_GSI_CFG,
    ECPRI_NFAPI_REASSEMBLY_VM_CFG_0_n,
    ECPRI_NFAPI_REASSEMBLY_VM_CFG_1_n,
    ECPRI_NFAPI_REASSEMBLY_VM_CFG_2_n,
    ECPRI_YELLOW_MARKER_BELOW,
    ECPRI_YELLOW_MARKER_BELOW_EN,
    ECPRI_RED_MARKER_BELOW,
    ECPRI_RED_MARKER_BELOW_EN,
    ECPRI_YELLOW_MARKER_SHADOW,
    ECPRI_RED_MARKER_SHADOW,
    ECPRI_YELLOW_MARKER_ABOVE,
    ECPRI_YELLOW_MARKER_ABOVE_EN,
    ECPRI_RED_MARKER_ABOVE,
    ECPRI_RED_MARKER_ABOVE_EN,
    ECPRI_QMB_CFG,
    ECPRI_QMB_0_STATUS,
    ECPRI_QMB_1_STATUS,
    ECPRI_QMB_CFG_PARAM,
    ECPRI_QMB0_SNOC_MONITOR_CNT,
    ECPRI_QMB1_SNOC_MONITOR_CNT,
    ECPRI_GSI_SNOC_MONITOR_CNT,
    ECPRI_GSI_TLV_FIFO_STATUS,
    ECPRI_GSI_AOS_FIFO_STATUS,
    ECPRI_GSI_EE_VFID,
    ECPRI_ENDP_DPL_CFG,
    ECPRI_DPL_TRIG_CTRL_n,
    ECPRI_DPL_TRIG_A_n,
    ECPRI_DPL_TRIG_B_n,
    ECPRI_SPARE_REG,
    ECPRI_DST_ACKMNGR_CMDQ_STATUS,
    ECPRI_STATE_GSI_IF,
    ECPRI_GEN_CFG,
    ECPRI_CLKON_CFG,
    ECPRI_AOS_CFG,
    ECPRI_TIMERS_XO_CLK_DIV_CFG,
    ECPRI_TIMERS_PULSE_GRAN_CFG,
    ECPRI_QTIME_LSB,
    ECPRI_QTIME_MSB,
    ECPRI_SNOC_FEC,
    ECPRI_SNOC_MONITORING_CFG,
    ECPRI_DST_ACKMNGR_CMDQ_STATUS_EMPTY,
    ECPRI_DST_ACKMNGR_CMDQ_COUNT,
    ECPRI_STATE_GSI_TLV_FIFO_EMPTY,
    ECPRI_STATE_GSI_AOS_FIFO_EMPTY,
    /* V2 */
    ECPRI_DMA_HW_PARAMS_1,
    ECPRI_DMA_RAM_FIFO_CONTENT_LINE_l_WORD_n,
    ECPRI_DMA_AHB2RAM_FIFOS_CFG,
    ECPRI_DMA_SNIFFER_CTRL1,
    ECPRI_DMA_SNIFFER_CTRL2,
    ECPRI_DMA_SNIFFER_STAT,
    ECPRI_DMA_LTE_DEBUG_CFG,
    ECPRI_DMA_LTE_WATERMARKS,
    ECPRI_DMA_STATUS_XBAR_FH_PORT_RX,
    ECPRI_DMA_STATUS_XBAR_FH_PORT_TX,
    ECPRI_DMA_STATUS_XBAR_C2C_PORT_RX,
    ECPRI_DMA_STATUS_XBAR_C2C_PORT_TX,
    ECPRI_DMA_INTERFACE_DDH_DF,
    ECPRI_DMA_INTERFACE_DF_C2C,
    ECPRI_DMA_INTERFACE_DF_NSO,
    ECPRI_DMA_INTERFACE_DF_FH,
    ECPRI_DMA_INTERFACE_DF_TXM,
    ECPRI_DMA_INTERFACE_DDH_TXM,
    ECPRI_DMA_STATUS_GSI0_A,
    ECPRI_DMA_STATUS_GSI0_B,
    ECPRI_DMA_STATUS_GSI1_A,
    ECPRI_DMA_STATUS_GSI1_B,
    ECPRI_DMA_STATUS_GSI2_A,
    ECPRI_DMA_STATUS_GSI2_B,
    ECPRI_DMA_XBAR_RX_PORT_DPL_STATUS,
    ECPRI_DMA_STATUS_XBAR_RX_PORT_m,
    ECPRI_DMA_STATUS_XBAR_RX_DROP,
    ECPRI_DMA_ENDP_LTE_CFG_GSI_m_CH_n,
    ECPRI_DMA_SDH_PREFETCH_LSB_GSI_m_CH_n,
    ECPRI_DMA_SDH_PREFETCH_MSB_GSI_m_CH_n,
    ECPRI_DMA_STATUS_LTE_PKT_DROP_FULL,
    ECPRI_DMA_RATE_LIMITER,
    ECPRI_DMA_DPL_MONITOR_CFG,
    ECPRI_DMA_DPL_MONITOR_CNT_0,
    ECPRI_DMA_DPL_MONITOR_CNT_1,
    ECPRI_DMA_REDIRECT_CHANNEL,
    ECPRI_DMA_STATUS_DST_DROP_PKT_GSI_m_REG_n,
    ECPRI_DMA_STATUS_DST_DROP_PKT_CLEAR,
    ECPRI_DMA_UNIT_CLK_ENABLE,
    ECPRI_DMA_LTE_CFG,
    ECPRI_DMA_STATUS_LTE_PKT_DROP_TLV_FIFO_EMPTY,
    ECPRI_DMA_LTE_LATENCY_BUFFER_WORD,
    ECPRI_DMA1_THROTTLE_THROTTLE_0_CNTRL,
    ECPRI_DMA1_THROTTLE_THROTTLE_0_CGC_CNTRL,
    ECPRI_DMA1_THROTTLE_THROTTLE_0_RESET_CNTRL,
    ECPRI_DMA1_THROTTLE_THROTTLE_0_CONFIG,
    ECPRI_DMA1_THROTTLE_THROTTLE_0_GRANT_PERIOD,
    ECPRI_DMA1_THROTTLE_THROTTLE_0_GRANT_COUNT,
    ECPRI_DMA1_THROTTLE_THROTTLE_0_THRESHOLD_00,
    ECPRI_DMA1_THROTTLE_THROTTLE_0_THRESHOLD_01,
    ECPRI_DMA1_THROTTLE_THROTTLE_0_THRESHOLD_02,
    ECPRI_DMA1_THROTTLE_THROTTLE_0_THRESHOLD_03,
    ECPRI_DMA1_THROTTLE_THROTTLE_0_PEAK_ACCUM_CREDIT,
    ECPRI_DMA1_THROTTLE_THROTTLE_0_DEBUG_CNTL,
    ECPRI_DMA1_THROTTLE_THROTTLE_0_DEBUG_READBACK,
    ECPRI_DMA1_THROTTLE_THROTTLE_0_CONFIG_CLK_CONTROL,
    ECPRI_DMA1_THROTTLE_THROTTLE_0_SPARE_REGS,
    ECPRI_DMA1_THROTTLE_BWMON_GLOBAL_INTERRUPT_STATUS,
    ECPRI_DMA1_THROTTLE_BWMON_GLOBAL_INTERRUPT_CLEAR,
    ECPRI_DMA1_THROTTLE_BWMON_GLOBAL_INTERRUPT_ENABLE,
    ECPRI_DMA1_THROTTLE_BWMON_INTERRUPT_STATUS,
    ECPRI_DMA1_THROTTLE_BWMON_INTERRUPT_CLEAR,
    ECPRI_DMA1_THROTTLE_BWMON_INTERRUPT_ENABLE,
    ECPRI_DMA1_THROTTLE_BWMON_CORE_CLOCKON_CONTROL,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_SW_RESET,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_CGC_CNTRL,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_ENABLE,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_CLEAR,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_BYTE_COUNT,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_THRESHOLD,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_MID_MASK,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_MID_MATCH,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON2_ENABLE,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON2_CLEAR,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON2_SAMPLING_WINDOW,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON2_BYTE_COUNT_THRESHOLD_HIGH,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON2_BYTE_COUNT_THRESHOLD_MEDIUM,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON2_BYTE_COUNT_THRESHOLD_LOW,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON2_ZONE_ACTIONS,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON2_ZONE_COUNT_THRESHOLD,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON2_BYTE_COUNT,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON2_WINDOW_TIMER,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON2_ZONE_COUNT,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON2_ZONEn_MAX_BYTE_COUNT,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_PID_MASK,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_PID_MATCH,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_BID_MASK,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_BID_MATCH,
    ECPRI_DMA1_THROTTLE_BWMON_STATS_COUNTER_INTERRUPT_STATUS,
    ECPRI_DMA1_THROTTLE_BWMON_STATS_COUNTER_INTERRUPT_CLEAR,
    ECPRI_DMA1_THROTTLE_BWMON_STATS_COUNTER_INTERRUPT_ENABLE,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_REJECT_COUNTERS_ENABLE,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_REJECT_PERIOD,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_ACCEPT_COUNT,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_REJECT_COUNT,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_IDLE_COUNT,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_INTR_TARGET,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_DEBUG_CNTL,
    ECPRI_DMA1_THROTTLE_BWMON_BWMON_DEBUG_READBACK,
    ECPRI_DMA0_THROTTLE_THROTTLE_0_CNTRL,
    ECPRI_DMA0_THROTTLE_THROTTLE_0_CGC_CNTRL,
    ECPRI_DMA0_THROTTLE_THROTTLE_0_RESET_CNTRL,
    ECPRI_DMA0_THROTTLE_THROTTLE_0_CONFIG,
    ECPRI_DMA0_THROTTLE_THROTTLE_0_GRANT_PERIOD,
    ECPRI_DMA0_THROTTLE_THROTTLE_0_GRANT_COUNT,
    ECPRI_DMA0_THROTTLE_THROTTLE_0_THRESHOLD_00,
    ECPRI_DMA0_THROTTLE_THROTTLE_0_THRESHOLD_01,
    ECPRI_DMA0_THROTTLE_THROTTLE_0_THRESHOLD_02,
    ECPRI_DMA0_THROTTLE_THROTTLE_0_THRESHOLD_03,
    ECPRI_DMA0_THROTTLE_THROTTLE_0_PEAK_ACCUM_CREDIT,
    ECPRI_DMA0_THROTTLE_THROTTLE_0_DEBUG_CNTL,
    ECPRI_DMA0_THROTTLE_THROTTLE_0_DEBUG_READBACK,
    ECPRI_DMA0_THROTTLE_THROTTLE_0_CONFIG_CLK_CONTROL,
    ECPRI_DMA0_THROTTLE_THROTTLE_0_SPARE_REGS,
    ECPRI_DMA0_THROTTLE_BWMON_GLOBAL_INTERRUPT_STATUS,
    ECPRI_DMA0_THROTTLE_BWMON_GLOBAL_INTERRUPT_CLEAR,
    ECPRI_DMA0_THROTTLE_BWMON_GLOBAL_INTERRUPT_ENABLE,
    ECPRI_DMA0_THROTTLE_BWMON_INTERRUPT_STATUS,
    ECPRI_DMA0_THROTTLE_BWMON_INTERRUPT_CLEAR,
    ECPRI_DMA0_THROTTLE_BWMON_INTERRUPT_ENABLE,
    ECPRI_DMA0_THROTTLE_BWMON_CORE_CLOCKON_CONTROL,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_SW_RESET,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_CGC_CNTRL,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_ENABLE,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_CLEAR,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_BYTE_COUNT,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_THRESHOLD,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_MID_MASK,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_MID_MATCH,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON2_ENABLE,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON2_CLEAR,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON2_SAMPLING_WINDOW,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON2_BYTE_COUNT_THRESHOLD_HIGH,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON2_BYTE_COUNT_THRESHOLD_MEDIUM,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON2_BYTE_COUNT_THRESHOLD_LOW,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON2_ZONE_ACTIONS,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON2_ZONE_COUNT_THRESHOLD,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON2_BYTE_COUNT,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON2_WINDOW_TIMER,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON2_ZONE_COUNT,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON2_ZONEn_MAX_BYTE_COUNT,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_PID_MASK,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_PID_MATCH,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_BID_MASK,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_BID_MATCH,
    ECPRI_DMA0_THROTTLE_BWMON_STATS_COUNTER_INTERRUPT_STATUS,
    ECPRI_DMA0_THROTTLE_BWMON_STATS_COUNTER_INTERRUPT_CLEAR,
    ECPRI_DMA0_THROTTLE_BWMON_STATS_COUNTER_INTERRUPT_ENABLE,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_REJECT_COUNTERS_ENABLE,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_REJECT_PERIOD,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_ACCEPT_COUNT,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_REJECT_COUNT,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_IDLE_COUNT,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_INTR_TARGET,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_DEBUG_CNTL,
    ECPRI_DMA0_THROTTLE_BWMON_BWMON_DEBUG_READBACK,
    DMA_REG_MAX,
};

/* Specific registers structures */

/* General registers structures */


/*
 * struct ecpri_dma_hal_reg_valmask - holding values and masking for registers
 *	HAL application may require only value and mask of it for some
 *	register fields.
 * @val - The value
 * @mask - Tha mask of the value
 */
struct ecpri_dma_hal_reg_valmask {
	u32 val;
	u32 mask;
};


/* Register HAL utility functions */

/*
 * ecpri_dma_hal_print_all_regs() - Loop and read and print all the valid registers
 *  Parameterized registers are also printed for all the valid ranges.
 *  Print to dmsg and IPC logs
 */
void ecpri_dma_hal_print_all_regs(bool print_to_dmesg);

/*
 * ecpri_dma_hal_reg_name_str() - returns string that represent the register
 * @reg_name: [in] register name
 */
const char *ecpri_dma_hal_reg_name_str(enum ecpri_dma_hal_reg_name reg_name);

/*
 * ecpri_dma_hal_read_reg_n() - Get the raw value of n parameterized reg
 */
u32 ecpri_dma_hal_read_reg_n(enum ecpri_dma_hal_reg_name reg, u32 n);

/*
 * ecpri_dma_hal_read_reg_mn() - Get mn parameterized reg value
 */
u32 ecpri_dma_hal_read_reg_mn(enum ecpri_dma_hal_reg_name reg, u32 m, u32 n);

/*
* ecpri_dma_hal_read_ep_reg_n() - Get n parameterized reg value according to ep
*/
u32 ecpri_dma_hal_read_ep_reg_n(enum ecpri_dma_hal_reg_name reg, u32 n, u32 ep_num);

/*
 * ecpri_dma_hal_write_reg_mn() - Write to m/n parameterized reg a raw value
 */
void ecpri_dma_hal_write_reg_mn(enum ecpri_dma_hal_reg_name reg, u32 m, u32 n, u32 val);

/*
* ecpri_dma_hal_write_reg_nk() - Write to n/k parameterized reg a raw value
*/
static inline void ecpri_dma_hal_write_reg_nk(
	enum ecpri_dma_hal_reg_name reg, u32 n, u32 k, u32 val)
{
	ecpri_dma_hal_write_reg_mn(reg, k, n, val);
}

/*
 * ecpri_dma_hal_write_reg_n() - Write to n parameterized reg a raw value
 */
static inline void ecpri_dma_hal_write_reg_n(enum ecpri_dma_hal_reg_name reg,
	u32 n, u32 val)
{
	ecpri_dma_hal_write_reg_mn(reg, 0, n, val);
}

/*
 * ecpri_dma_hal_read_reg_n_fields() - Get the parsed value of n parameterized reg
 */
u32 ecpri_dma_hal_read_reg_n_fields(enum ecpri_dma_hal_reg_name reg, u32 n, void *fields);


/*
 * ecpri_dma_hal_write_reg_fields() - Write to parameterized reg a prased value
 */
void ecpri_dma_hal_write_reg_fields(enum ecpri_dma_hal_reg_name reg,
    const void* fields);

/*
 * ecpri_dma_hal_write_reg_n_fields() - Write to n parameterized reg a prased value
 */
void ecpri_dma_hal_write_reg_n_fields(enum ecpri_dma_hal_reg_name reg, u32 n,
	const void *fields);

/*
 * ecpri_dma_hal_read_reg_mn_fields() - Get the parsed value of mn parameterized
 * reg
 */
u32 ecpri_dma_hal_read_reg_mn_fields(enum ecpri_dma_hal_reg_name reg, u32 m,
    u32 n, void* fields);

/*
 * ecpri_dma_hal_write_reg_mn_fields() - Write to mn parameterized reg a prased
 * value
 */
void ecpri_dma_hal_write_reg_mn_fields(enum ecpri_dma_hal_reg_name reg,
    u32 m, u32 n, const void *fields);

/*
 * ecpri_dma_hal_read_reg() - Get the raw value of a reg
 */
static inline u32 ecpri_dma_hal_read_reg(enum ecpri_dma_hal_reg_name reg)
{
	return ecpri_dma_hal_read_reg_n(reg, 0);
}

u32 ecpri_dma_hal_read_reg_fields(enum ecpri_dma_hal_reg_name reg, void* fields);

/*
 * ecpri_dma_hal_read_ep_reg() - Get the raw value of a ep reg
 */
u32 ecpri_dma_hal_read_ep_reg(enum ecpri_dma_hal_reg_name reg, u32 ep_num);

/*
 * ecpri_dma_hal_write_reg() - Write to reg a raw value
 */
static inline void ecpri_dma_hal_write_reg(enum ecpri_dma_hal_reg_name reg,
	u32 val)
{
	ecpri_dma_hal_write_reg_mn(reg, 0, 0, val);
}

/*
 * ecpri_dma_hal_write_ep_reg() - Write to ep reg a raw value
 */
void ecpri_dma_hal_write_ep_reg(enum ecpri_dma_hal_reg_name reg, u32 ep_num, u32 val);

/*
 * ecpri_dma_hal_write_ep_reg_n() - Write to ep reg a raw value of n parameterized reg
 */
void ecpri_dma_hal_write_ep_reg_n(enum ecpri_dma_hal_reg_name reg, u32 n, u32 ep_num, u32 val);

/*
 * Get the offset of a m/n parameterized register
 */
u32 ecpri_dma_hal_get_reg_mn_ofst(enum ecpri_dma_hal_reg_name reg, u32 m, u32 n);

/*
* Get the offset of a n,k register
*/
u32 ecpri_dma_hal_get_reg_nk_offset(enum ecpri_dma_hal_reg_name reg, u32 n, u32 l);

/*
 * Get the offset of a n parameterized register
 */
static inline u32 ecpri_dma_hal_get_reg_n_ofst(enum ecpri_dma_hal_reg_name reg, u32 n)
{
	return ecpri_dma_hal_get_reg_mn_ofst(reg, 0, n);
}

/*
 * Get the offset of a ep register according to ep index
 */
u32 ecpri_dma_hal_get_ep_reg_offset(enum ecpri_dma_hal_reg_name reg, u32 ep_num);

/*
 * Get the offset of a register
 */
static inline u32 ecpri_dma_hal_get_reg_ofst(enum ecpri_dma_hal_reg_name reg)
{
	return ecpri_dma_hal_get_reg_mn_ofst(reg, 0, 0);
}

/*
 * Get the register base address
 */
u32 ecpri_dma_hal_get_reg_base(void);

#endif /* _DMAHAL_REG_H_ */
