/* SPDX-License-Identifier: GPL-2.0-only
 * Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
 */

/**
  @file qcom_aw_phy_debugfs_dir_struct.h
  @brief Header file for the debugfs directory structure of AW PHY driver parameters.
*/

#ifndef QCOM_AW_PHY_DEBUGFS_H
#define QCOM_AW_PHY_DEBUGFS_H

#define TREE "\
{ \
	phy_enable_status \
	{ \
		common \
		{ \
			,loopback_mode \
			,ref_clock \
			,no_of_ports \
			,aw_fw_ver \
		} \
		phy0 \
		{ \
			info \
			{ \
				,info:mode:00 \
				,info:bu_status:00 \
				,info:num_of_lanes_enabled:00 \
				,info:sfp_port_type:00 \
			} \
			lane \
			{ \
				lane0 \
				{ \
					,lane:enable_status:00 \
					,lane:speed:00 \
					,lane:cdr_lock_status:00 \
					,lane:pcs_link_status:00 \
					,lane:mac_link_index:00 \
				} \
				lane1 \
				{ \
					,lane:enable_status:01 \
					,lane:speed:01 \
					,lane:cdr_lock_status:01 \
					,lane:pcs_link_status:01 \
					,lane:mac_link_index:01 \
				} \
				lane2 \
				{ \
					,lane:enable_status:02 \
					,lane:speed:02 \
					,lane:cdr_lock_status:02 \
					,lane:pcs_link_status:02 \
					,lane:mac_link_index:02 \
				} \
				lane3 \
				{ \
					,lane:enable_status:03 \
					,lane:speed:03 \
					,lane:cdr_lock_status:03 \
					,lane:pcs_link_status:03 \
					,lane:mac_link_index:03 \
				} \
			} \
		} \
		phy1 \
		{ \
			info \
			{ \
				,info:mode:10 \
				,info:bu_status:10 \
				,info:num_of_lanes_enabled:10 \
				,info:sfp_port_type:10 \
			} \
			lane \
			{ \
				lane0 \
				{ \
					,lane:enable_status:10 \
					,lane:speed:10 \
					,lane:cdr_lock_status:10 \
					,lane:pcs_link_status:10 \
					,lane:mac_link_index:10 \
				} \
				lane1 \
				{ \
					,lane:enable_status:11 \
					,lane:speed:11 \
					,lane:cdr_lock_status:11 \
					,lane:pcs_link_status:11 \
					,lane:mac_link_index:11 \
				} \
				lane2 \
				{ \
					,lane:enable_status:12 \
					,lane:speed:12 \
					,lane:cdr_lock_status:12 \
					,lane:pcs_link_status:12 \
					,lane:mac_link_index:12 \
				} \
				lane3 \
				{ \
					,lane:enable_status:13 \
					,lane:speed:13 \
					,lane:cdr_lock_status:13 \
					,lane:pcs_link_status:13 \
					,lane:mac_link_index:13 \
				} \
			} \
		} \
		phy2 \
		{ \
			info \
			{ \
				,info:mode:20 \
				,info:bu_status:20 \
				,info:num_of_lanes_enabled:20 \
				,info:sfp_port_type:20 \
			} \
			lane \
			{ \
				lane0 \
				{ \
					,lane:enable_status:20 \
					,lane:speed:20 \
					,lane:cdr_lock_status:20 \
					,lane:pcs_link_status:20 \
					,lane:mac_link_index:20 \
				} \
				lane1 \
				{ \
					,lane:enable_status:21 \
					,lane:speed:21 \
					,lane:cdr_lock_status:21 \
					,lane:pcs_link_status:21 \
					,lane:mac_link_index:21 \
				} \
				lane2 \
				{ \
					,lane:enable_status:22 \
					,lane:speed:22 \
					,lane:cdr_lock_status:22 \
					,lane:pcs_link_status:22 \
					,lane:mac_link_index:22 \
				} \
				lane3 \
				{ \
					,lane:enable_status:23 \
					,lane:speed:23 \
					,lane:cdr_lock_status:23 \
					,lane:pcs_link_status:23 \
					,lane:mac_link_index:23 \
				} \
			} \
		} \
		phy3 \
		{ \
			info \
			{ \
				,info:mode:30 \
				,info:bu_status:30 \
				,info:num_of_lanes_enabled:30 \
				,info:sfp_port_type:30 \
			} \
			lane \
			{ \
				lane0 \
				{ \
					,lane:enable_status:30 \
					,lane:speed:30 \
					,lane:cdr_lock_status:30 \
					,lane:pcs_link_status:30 \
					,lane:mac_link_index:30 \
				} \
				lane1 \
				{ \
					,lane:enable_status:31 \
					,lane:speed:31 \
					,lane:cdr_lock_status:31 \
					,lane:pcs_link_status:31 \
					,lane:mac_link_index:31 \
				} \
				lane2 \
				{ \
					,lane:enable_status:32 \
					,lane:speed:32 \
					,lane:cdr_lock_status:32 \
					,lane:pcs_link_status:32 \
					,lane:mac_link_index:32 \
				} \
				lane3 \
				{ \
					,lane:enable_status:33 \
					,lane:speed:33 \
					,lane:cdr_lock_status:33 \
					,lane:pcs_link_status:33 \
					,lane:mac_link_index:33 \
				} \
			} \
		} \
		phy4 \
		{ \
			info \
			{ \
				,info:mode:40 \
				,info:bu_status:40 \
				,info:num_of_lanes_enabled:40 \
				,info:sfp_port_type:40 \
			} \
			lane \
			{ \
				lane0 \
				{ \
					,lane:enable_status:40 \
					,lane:speed:40 \
					,lane:cdr_lock_status:40 \
					,lane:pcs_link_status:40 \
					,lane:mac_link_index:40 \
				} \
				lane1 \
				{ \
					,lane:enable_status:41 \
					,lane:speed:41 \
					,lane:cdr_lock_status:41 \
					,lane:pcs_link_status:41 \
					,lane:mac_link_index:41 \
				} \
				lane2 \
				{ \
					,lane:enable_status:42 \
					,lane:speed:42 \
					,lane:cdr_lock_status:42 \
					,lane:pcs_link_status:42 \
					,lane:mac_link_index:42 \
				} \
				lane3 \
				{ \
					,lane:enable_status:43 \
					,lane:speed:43 \
					,lane:cdr_lock_status:43 \
					,lane:pcs_link_status:43 \
					,lane:mac_link_index:43 \
				} \
			} \
		} \
	} \
} \
"
#endif
