
DATACSMKERNELTOP = $(ROOTDIR)datacsm-kernel/drivers/
ECPRIOXTOR = $(DATACSMKERNELTOP)/ecpri/ecpri_oxtor

LINUX_INC +=	-Iinclude/linux

CDEFINES +=	-DANI_LITTLE_BYTE_ENDIAN \
	-DANI_LITTLE_BIT_ENDIAN \
	-DDOT11F_LITTLE_ENDIAN_HOST \
	-DANI_COMPILER_TYPE_GCC \
	-DANI_OS_TYPE_ANDROID=6 \
	-DPTT_SOCK_SVC_ENABLE \
	-Wall\
	-Werror\
	-D__linux__

KBUILD_CPPFLAGS += $(CDEFINES)

ccflags-y += $(LINUX_INC)
ccflags-y += -I$(DATACSMKERNELTOP)/include/
ccflags-y += -I$(ECPRIOXTOR)/include/
ccflags-y += -I$(ECPRIOXTOR)/include/uapi/ecpri/

header-y += $(ECPRIOXTOR)/include/uapi/ecpri/ecpriss_flow.h

ifeq ($(call cc-option-yn, -Wmaybe-uninitialized),y)
EXTRA_CFLAGS += -Wmaybe-uninitialized
endif

ifeq ($(call cc-option-yn, -Wheader-guard),y)
EXTRA_CFLAGS += -Wheader-guard
endif

ifneq ($(MODNAME), qdsp6v2)
CHIP_NAME ?= $(MODNAME)
CDEFINES += -DMULTI_IF_NAME=\"$(CHIP_NAME)\"
endif

obj-$(CONFIG_ECPRI_OXTOR) += ecpri_oxtor.o
ecpri_oxtor-$(CONFIG_ECPRI_OXTOR) += \
		src/ecpri_oxtor_core.o \
		src/ecpri_oxtor_hal.o \
		src/ecpri_oxtor_tx.o \
		src/ecpri_oxtor_rx.o \
		src/ecpri_oxtor_debugfs.o

