
ccflags-y := -Ofast

# Allow warnings to fail builds
#ccflags-y += -Wall -Werror

# Enable additional warnings that are compatible with kernel headers
ccflags-y += -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-cast-function-type

# Features enabled
ccflags-y += -DENABLE_USE_FIRMWARE_FILE
ccflags-y += -DCONFIG_ASPM -DENABLE_S5WOL -DENABLE_EEE -DENABLE_TX_NO_CLOSE -DCONFIG_R8168_NAPI -DCONFIG_R8168_VLAN


obj-m += r8168.o

r8168-y := r8168_n.o \
		   rtl_eeprom.o \
		   r8168_asf.o \
		   rtltool.o \
		   r8168_firmware.o
